### ISSUE TITLE
Can‘t Reproduce the result in paper

### ISSUE THREAD

**Issue by MoringLotus** [xiaojieli0903/Mamba-FSCIL#1]
I follow your step to reproduce the result in CUB dataset， but 2024-11-17 17:34:22,815 - mmcls - INFO - 77.13 70.60 65.66 61.02 58.22 54.67 51.95 49.73 47.54 45.78 43.56 ， which has a big gap with your paper
![image](https://github.com/user-attachments/assets/67e7dad6-e43b-4081-99ef-e40b1154b224)

**Comment by xiaojieli0903** [comment]
Hi @MoringLotus,  

Thank you for your interest in our work. To better assist you, could you please provide details about your training environment, such as the GPU model, PyTorch version, and other relevant configurations? Additionally, it would be helpful if you could share the specific commands or scripts you used to run the experiments.  

Please note that our experiments were conducted using **8 GPUs**. If you are using a single GPU, ensure that the **overall batch size** remains consistent with our setup. You can refer to the scaling principle described in [this paper](https://arxiv.org/abs/1706.02677) (Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour) to adjust the batch size appropriately.  

Looking forward to your response!  

Best regards,  
Xiaojie Li

**Comment by xiaojieli0903** [comment]
Hi @MoringLotus,

We haven’t received further updates from you regarding your reproduction setup and results. To keep the issue list organized, I have closed this issue.

If you have any additional questions or would like to continue the discussion, please feel free to reopen this issue at any time. We’re happy to help!

Best regards,
Xiaojie Li
